"""Generate C source code for a bit-parallel NFA matcher."""

from __future__ import annotations


def _mask_lit(value: int, bits: int) -> str:
    """Format *value* as a C unsigned hex literal of the chosen width."""
    if bits <= 8:
        return f"0x{value & 0xff:02x}u"
    if bits <= 16:
        return f"0x{value & 0xffff:04x}u"
    return f"0x{value & 0xffffffff:08x}u"


def _byte_designator(b: int) -> str:
    """Return a C array designator for byte *b*."""
    if 32 <= b <= 126:
        c = chr(b)
        if c == "'":
            return "['\\'']"
        if c == "\\":
            return "['\\\\']"
        return f"['{c}']"
    return f"[{b}]"


# ---------------------------------------------------------------------------
# Single-word variants (uint8 / uint16 / uint32)
# ---------------------------------------------------------------------------

def _emit_single_word(
    nfa: dict,
    state_t: str,
    bits: int,
    *,
    prefix: str,
    emit_main: bool,
    pattern: str | None,
    flags: str,
    encoding: str,
) -> str:
    num_pos = nfa["num_positions"]
    initial = nfa["initial"]
    accept = nfa["accept"]
    trans_masks = nfa["trans_masks"]

    # Positions with at least one non-zero transition
    active_positions = [p for p in range(num_pos) if trans_masks[p]]

    lines: list[str] = []
    lines.append("/* Generated by regex-cgen – do not edit. */")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    if emit_main:
        lines.append("#include <string.h>")
        lines.append("#include <stdio.h>")
    lines.append("")

    # Transition table
    lines.append(
        f"static const {state_t} {prefix}_trans[{num_pos}][256] = {{"
    )
    for p in range(num_pos):
        masks = trans_masks[p]
        non_zero = sorted((b, v) for b, v in masks.items() if v != 0)
        if not non_zero:
            row_str = "{ 0 }"
        else:
            entries = []
            for b, v in non_zero:
                entries.append(f"{_byte_designator(b)} = {_mask_lit(v, bits)}")
            row_str = "{ " + ", ".join(entries) + " }"
        lines.append(f"    /* position {p} */ {row_str},")
    lines.append("};")
    lines.append("")

    # Metadata comment
    if pattern is not None:
        lines.append(f'/* regex:    "{pattern}"')
        lines.append(f' * flags:    "{flags}"')
        lines.append(f" * encoding: {encoding}")
        lines.append(f" * engine:   bitnfa ({state_t})")
        lines.append(" */")
    else:
        lines.append(f"/* engine: bitnfa ({state_t}) */")

    # Match function
    func_name = f"{prefix}_match"
    lines.append(f"bool {func_name}(const char *input, size_t len) {{")
    lines.append(f"    {state_t} state = {_mask_lit(initial, bits)};")
    lines.append("    for (size_t i = 0; i < len; i++) {")
    lines.append("        unsigned char b = (unsigned char)input[i];")
    lines.append(f"        {state_t} next = 0;")
    for p in active_positions:
        lines.append(
            f"        if (state & {_mask_lit(1 << p, bits)}) "
            f"next |= {prefix}_trans[{p}][b];"
        )
    lines.append("        state = next;")
    lines.append("    }")
    lines.append(f"    return (state & {_mask_lit(accept, bits)}) != 0;")
    lines.append("}")

    if emit_main:
        _append_main(lines, func_name)

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Multi-word variant (uint32_t array)
# ---------------------------------------------------------------------------

def _emit_array_variant(
    nfa: dict,
    num_words: int,
    *,
    prefix: str,
    emit_main: bool,
    pattern: str | None,
    flags: str,
    encoding: str,
) -> str:
    num_pos = nfa["num_positions"]
    initial = nfa["initial"]
    accept = nfa["accept"]
    trans_masks = nfa["trans_masks"]

    def to_words(v: int) -> list[int]:
        return [(v >> (w * 32)) & 0xFFFFFFFF for w in range(num_words)]

    init_words = to_words(initial)
    accept_words = to_words(accept)

    active_positions = [p for p in range(num_pos) if trans_masks[p]]

    lines: list[str] = []
    lines.append("/* Generated by regex-cgen – do not edit. */")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    if emit_main:
        lines.append("#include <string.h>")
        lines.append("#include <stdio.h>")
    lines.append("")

    # Transition table: [num_pos][256][num_words]
    lines.append(
        f"static const uint32_t {prefix}_trans[{num_pos}][256][{num_words}] = {{"
    )
    for p in range(num_pos):
        masks = trans_masks[p]
        non_zero = sorted((b, v) for b, v in masks.items() if v != 0)
        if not non_zero:
            lines.append(f"    /* position {p} */ {{ 0 }},")
        else:
            entries = []
            for b, v in non_zero:
                words = to_words(v)
                word_str = ", ".join(f"0x{w:08x}u" for w in words)
                entries.append(f"{_byte_designator(b)} = {{ {word_str} }}")
            row_str = "{ " + ", ".join(entries) + " }"
            lines.append(f"    /* position {p} */ {row_str},")
    lines.append("};")
    lines.append("")

    # Metadata comment
    if pattern is not None:
        lines.append(f'/* regex:    "{pattern}"')
        lines.append(f' * flags:    "{flags}"')
        lines.append(f" * encoding: {encoding}")
        lines.append(f" * engine:   bitnfa (uint32_t[{num_words}])")
        lines.append(" */")
    else:
        lines.append(f"/* engine: bitnfa (uint32_t[{num_words}]) */")

    # Match function
    func_name = f"{prefix}_match"
    lines.append(f"bool {func_name}(const char *input, size_t len) {{")
    for w in range(num_words):
        lines.append(f"    uint32_t s{w} = 0x{init_words[w]:08x}u;")
    lines.append("    for (size_t i = 0; i < len; i++) {")
    lines.append("        unsigned char b = (unsigned char)input[i];")
    for w in range(num_words):
        lines.append(f"        uint32_t n{w} = 0;")
    # Fully unrolled position checks
    for p in active_positions:
        word_idx = p // 32
        bit_idx = p % 32
        bit_mask = f"0x{1 << bit_idx:08x}u"
        assigns = " ".join(
            f"n{w} |= {prefix}_trans[{p}][b][{w}];" for w in range(num_words)
        )
        lines.append(f"        if (s{word_idx} & {bit_mask}) {{ {assigns} }}")
    for w in range(num_words):
        lines.append(f"        s{w} = n{w};")
    lines.append("    }")
    # Accept check – fully unrolled, no loops
    accept_parts = []
    for w in range(num_words):
        if accept_words[w]:
            accept_parts.append(f"(s{w} & 0x{accept_words[w]:08x}u)")
    if accept_parts:
        lines.append(f"    return ({' || '.join(accept_parts)}) != 0;")
    else:
        lines.append("    return false;")
    lines.append("}")

    if emit_main:
        _append_main(lines, func_name)

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _append_main(lines: list[str], func_name: str) -> None:
    lines.append("")
    lines.append("int main(int argc, char *argv[]) {")
    lines.append("    if (argc != 2) {")
    lines.append('        fprintf(stderr, "Usage: %s <input>\\n", argv[0]);')
    lines.append("        return 2;")
    lines.append("    }")
    lines.append(f"    return {func_name}(argv[1], strlen(argv[1])) ? 0 : 1;")
    lines.append("}")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_bitnfa_c_code(
    nfa: dict,
    *,
    prefix: str = "regex",
    emit_main: bool = False,
    pattern: str | None = None,
    flags: str = "",
    encoding: str = "utf8",
) -> str:
    """Emit C code for a bit-parallel NFA matcher.

    The variant (``uint8_t``, ``uint16_t``, ``uint32_t``, or
    ``uint32_t[N]``) is chosen automatically based on *num_positions*.
    """
    num_pos = nfa["num_positions"]

    if num_pos <= 8:
        state_t, bits = "uint8_t", 8
    elif num_pos <= 16:
        state_t, bits = "uint16_t", 16
    elif num_pos <= 32:
        state_t, bits = "uint32_t", 32
    else:
        num_words = (num_pos + 31) // 32
        return _emit_array_variant(
            nfa,
            num_words,
            prefix=prefix,
            emit_main=emit_main,
            pattern=pattern,
            flags=flags,
            encoding=encoding,
        )

    return _emit_single_word(
        nfa,
        state_t,
        bits,
        prefix=prefix,
        emit_main=emit_main,
        pattern=pattern,
        flags=flags,
        encoding=encoding,
    )
