"""Generate C source code from a compiled DFA."""

from __future__ import annotations

from .compiler import compile_regex


def generate_c_code(
    dfa: dict,
    *,
    prefix: str = "regex",
    emit_main: bool = False,
) -> str:
    """Emit C code for a table-driven DFA matcher.

    The generated code contains:

    * A ``static const`` transition table (``{prefix}_transitions``).
    * A match function named ``{prefix}_match`` with the signature::

          bool {prefix}_match(const char *input, size_t len);

    States are ordered so that all accepting states have indices >=
    ``first_accept``; the match function uses ``return state >= first_accept;``
    as the acceptance test (no boolean lookup table required).

    When *emit_main* is ``True`` an additional ``main`` function is emitted
    that reads ``argv[1]`` and returns exit-code **0** on match, **1** on
    mismatch, and **2** on usage error.
    """
    n = dfa["num_states"]
    initial = dfa["initial"]
    first_accept = dfa["first_accept"]
    trans = dfa["transitions"]

    # Choose the narrowest unsigned type that fits
    if n <= 256:
        state_t = "uint8_t"
    elif n <= 65536:
        state_t = "uint16_t"
    else:
        state_t = "uint32_t"

    lines: list[str] = []
    lines.append("/* Generated by regex-cgen – do not edit. */")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    if emit_main:
        lines.append("#include <string.h>")
        lines.append("#include <stdio.h>")
    lines.append("")

    # Transition table – deduplicate identical rows
    unique_rows: list[tuple[int, ...]] = []
    row_index: dict[tuple[int, ...], int] = {}
    state_to_row: list[int] = []
    for s in range(n):
        row = tuple(trans.get((s, b), 0) for b in range(256))
        if row not in row_index:
            row_index[row] = len(unique_rows)
            unique_rows.append(row)
        state_to_row.append(row_index[row])

    num_unique = len(unique_rows)
    lines.append(
        f"static const {state_t} {prefix}_transitions[{num_unique}][256] = {{"
    )
    for row in unique_rows:
        lines.append(f"    {{{', '.join(str(v) for v in row)}}},")
    lines.append("};")
    lines.append("")

    # Row-index map: state → index into {prefix}_transitions (only when needed)
    if num_unique < n:
        if num_unique <= 256:
            row_t = "uint8_t"
        elif num_unique <= 65536:
            row_t = "uint16_t"
        else:
            row_t = "uint32_t"
        lines.append(f"static const {row_t} {prefix}_row_map[{n}] = {{")
        lines.append(f"    {', '.join(str(i) for i in state_to_row)}")
        lines.append("};")
        lines.append("")

    # Match function
    func_name = f"{prefix}_match"
    lines.append(f"bool {func_name}(const char *input, size_t len) {{")
    lines.append(f"    {state_t} state = {initial};")
    lines.append("    for (size_t i = 0; i < len; i++) {")
    if num_unique < n:
        lines.append(
            f"        state = {prefix}_transitions"
            f"[{prefix}_row_map[state]][(unsigned char)input[i]];"
        )
    else:
        lines.append(
            f"        state = {prefix}_transitions[state][(unsigned char)input[i]];"
        )
    lines.append("    }")
    lines.append(f"    return state >= {first_accept};")
    lines.append("}")

    if emit_main:
        lines.append("")
        lines.append("int main(int argc, char *argv[]) {")
        lines.append("    if (argc != 2) {")
        lines.append(
            '        fprintf(stderr, "Usage: %s <input>\\n", argv[0]);'
        )
        lines.append("        return 2;")
        lines.append("    }")
        lines.append(
            f"    return {func_name}(argv[1], strlen(argv[1])) ? 0 : 1;"
        )
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def generate(
    pattern: str,
    flags: str = "",
    *,
    emit_main: bool = False,
    prefix: str = "regex",
    encoding: str = "utf8",
) -> str:
    """High-level API: compile *pattern* and return generated C code.

    Parameters
    ----------
    pattern:
        Regular expression (re2-compatible subset).
    flags:
        Flag characters: ``i`` (case-insensitive), ``s`` (dot-all),
        ``m`` (multiline), ``x`` (verbose).
    emit_main:
        When ``True``, emit a ``main()`` function that reads ``argv[1]``
        and returns exit-code 0/1/2.
    prefix:
        Prefix for all generated C identifiers: arrays are named
        ``{prefix}_transitions``, ``{prefix}_row_map``
        and the match function is named ``{prefix}_match``.
        Defaults to ``"regex"``.
    encoding:
        ``"utf8"`` (default) for Unicode/UTF-8 semantics; ``"bytes"`` for
        raw byte semantics where ``.`` matches any single byte and
        literals/classes operate on byte values 0-255.
    """
    dfa = compile_regex(pattern, flags, encoding=encoding)
    return generate_c_code(dfa, prefix=prefix, emit_main=emit_main)
