"""Generate C source code from a compiled DFA."""

from __future__ import annotations

from .compiler import compile_regex


def generate_c_code(
    dfa: dict,
    *,
    func_name: str = "regex_match",
    emit_main: bool = False,
) -> str:
    """Emit C code for a table-driven DFA matcher.

    The generated code contains:

    * A ``static const`` transition table (``dfa_transitions``).
    * A ``static const`` accept-state table (``dfa_accept``).
    * A match function (default name ``regex_match``) with the signature::

          bool regex_match(const char *input, size_t len);

    When *emit_main* is ``True`` an additional ``main`` function is emitted
    that reads ``argv[1]`` and returns exit-code **0** on match, **1** on
    mismatch, and **2** on usage error.
    """
    n = dfa["num_states"]
    initial = dfa["initial"]
    accept = dfa["accept"]
    trans = dfa["transitions"]

    # Choose the narrowest unsigned type that fits
    if n <= 256:
        state_t = "uint8_t"
    elif n <= 65536:
        state_t = "uint16_t"
    else:
        state_t = "uint32_t"

    lines: list[str] = []
    lines.append("/* Generated by regex-cgen – do not edit. */")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stdint.h>")
    if emit_main:
        lines.append("#include <string.h>")
        lines.append("#include <stdio.h>")
    lines.append("")

    # Transition table
    lines.append(
        f"static const {state_t} dfa_transitions[{n}][256] = {{"
    )
    for s in range(n):
        row = [str(trans.get((s, b), 0)) for b in range(256)]
        lines.append(f"    {{{', '.join(row)}}},")
    lines.append("};")
    lines.append("")

    # Accept table
    accept_vals = ["true" if s in accept else "false" for s in range(n)]
    lines.append(f"static const bool dfa_accept[{n}] = {{")
    lines.append(f"    {', '.join(accept_vals)}")
    lines.append("};")
    lines.append("")

    # Match function
    lines.append(f"bool {func_name}(const char *input, size_t len) {{")
    lines.append(f"    {state_t} state = {initial};")
    lines.append("    for (size_t i = 0; i < len; i++) {")
    lines.append(
        "        state = dfa_transitions[state][(unsigned char)input[i]];"
    )
    lines.append("    }")
    lines.append("    return dfa_accept[state];")
    lines.append("}")

    if emit_main:
        lines.append("")
        lines.append("int main(int argc, char *argv[]) {")
        lines.append("    if (argc != 2) {")
        lines.append(
            '        fprintf(stderr, "Usage: %s <input>\\n", argv[0]);'
        )
        lines.append("        return 2;")
        lines.append("    }")
        lines.append(
            f"    return {func_name}(argv[1], strlen(argv[1])) ? 0 : 1;"
        )
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def generate(
    pattern: str,
    flags: str = "",
    *,
    emit_main: bool = False,
    func_name: str = "regex_match",
    encoding: str = "utf8",
) -> str:
    """High-level API: compile *pattern* and return generated C code.

    Parameters
    ----------
    pattern:
        Regular expression (re2-compatible subset).
    flags:
        Flag characters: ``i`` (case-insensitive), ``s`` (dot-all),
        ``m`` (multiline), ``x`` (verbose).
    emit_main:
        When ``True``, emit a ``main()`` function that reads ``argv[1]``
        and returns exit-code 0/1/2.
    func_name:
        Name of the generated C match function.
    encoding:
        ``"utf8"`` (default) for Unicode/UTF-8 semantics; ``"bytes"`` for
        raw byte semantics where ``.`` matches any single byte and
        literals/classes operate on byte values 0-255.
    """
    dfa = compile_regex(pattern, flags, encoding=encoding)
    return generate_c_code(dfa, func_name=func_name, emit_main=emit_main)
