/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint16_t regex_trans[11][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { ['c'] = 0x0004u },
    /* position 2 */ { ['a'] = 0x0008u },
    /* position 3 */ { ['t'] = 0x0001u },
    /* position 4 */ { ['d'] = 0x0020u },
    /* position 5 */ { ['o'] = 0x0040u },
    /* position 6 */ { ['g'] = 0x0001u },
    /* position 7 */ { ['f'] = 0x0100u },
    /* position 8 */ { ['i'] = 0x0200u },
    /* position 9 */ { ['s'] = 0x0400u },
    /* position 10 */ { ['h'] = 0x0001u },
};

/* regex:    "cat|dog|fish"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint16_t)
 */
bool regex_match(const char *input, size_t len) {
    uint16_t state = 0x0092u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint16_t next = 0;
        if (state & 0x0002u) next |= regex_trans[1][b];
        if (state & 0x0004u) next |= regex_trans[2][b];
        if (state & 0x0008u) next |= regex_trans[3][b];
        if (state & 0x0010u) next |= regex_trans[4][b];
        if (state & 0x0020u) next |= regex_trans[5][b];
        if (state & 0x0040u) next |= regex_trans[6][b];
        if (state & 0x0080u) next |= regex_trans[7][b];
        if (state & 0x0100u) next |= regex_trans[8][b];
        if (state & 0x0200u) next |= regex_trans[9][b];
        if (state & 0x0400u) next |= regex_trans[10][b];
        state = next;
    }
    return (state & 0x0001u) != 0;
}
