/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "cat|dog|fish"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint16_t)
 */
bool regex_match(const char *input, size_t len) {
    uint16_t state = 0x0092u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint16_t next = 0;
        if (state & 0x0002u) next |= ((b == 'c') ? 0x0004u : 0u);
        if (state & 0x0004u) next |= ((b == 'a') ? 0x0008u : 0u);
        if (state & 0x0008u) next |= ((b == 't') ? 0x0001u : 0u);
        if (state & 0x0010u) next |= ((b == 'd') ? 0x0020u : 0u);
        if (state & 0x0020u) next |= ((b == 'o') ? 0x0040u : 0u);
        if (state & 0x0040u) next |= ((b == 'g') ? 0x0001u : 0u);
        if (state & 0x0080u) next |= ((b == 'f') ? 0x0100u : 0u);
        if (state & 0x0100u) next |= ((b == 'i') ? 0x0200u : 0u);
        if (state & 0x0200u) next |= ((b == 's') ? 0x0400u : 0u);
        if (state & 0x0400u) next |= ((b == 'h') ? 0x0001u : 0u);
        state = next;
    }
    return (state & 0x0001u) != 0;
}
