/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_transitions[9][256] = {
    /* states 0, 9 */ { 0 },
    /* state 1 */ { ['c'] = 2, ['d'] = 5, ['f'] = 4 },
    /* state 2 */ { ['a'] = 6 },
    /* state 3 */ { ['s'] = 7 },
    /* state 4 */ { ['i'] = 3 },
    /* state 5 */ { ['o'] = 8 },
    /* state 6 */ { ['t'] = 9 },
    /* state 7 */ { ['h'] = 9 },
    /* state 8 */ { ['g'] = 9 },
};

static const uint8_t regex_row_map[10] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 0
};

bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[regex_row_map[state]][(unsigned char)input[i]];
    }
    return state >= 9;
}
