/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "abcdefghijklmnopq"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t)
 */
bool regex_match(const char *input, size_t len) {
    uint32_t state = 0x00000001u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t next = 0;
        if (state & 0x00000001u) next |= ((b == 'a') ? 0x00000002u : 0u);
        if (state & 0x00000002u) next |= ((b == 'b') ? 0x00000004u : 0u);
        if (state & 0x00000004u) next |= ((b == 'c') ? 0x00000008u : 0u);
        if (state & 0x00000008u) next |= ((b == 'd') ? 0x00000010u : 0u);
        if (state & 0x00000010u) next |= ((b == 'e') ? 0x00000020u : 0u);
        if (state & 0x00000020u) next |= ((b == 'f') ? 0x00000040u : 0u);
        if (state & 0x00000040u) next |= ((b == 'g') ? 0x00000080u : 0u);
        if (state & 0x00000080u) next |= ((b == 'h') ? 0x00000100u : 0u);
        if (state & 0x00000100u) next |= ((b == 'i') ? 0x00000200u : 0u);
        if (state & 0x00000200u) next |= ((b == 'j') ? 0x00000400u : 0u);
        if (state & 0x00000400u) next |= ((b == 'k') ? 0x00000800u : 0u);
        if (state & 0x00000800u) next |= ((b == 'l') ? 0x00001000u : 0u);
        if (state & 0x00001000u) next |= ((b == 'm') ? 0x00002000u : 0u);
        if (state & 0x00002000u) next |= ((b == 'n') ? 0x00004000u : 0u);
        if (state & 0x00004000u) next |= ((b == 'o') ? 0x00008000u : 0u);
        if (state & 0x00008000u) next |= ((b == 'p') ? 0x00010000u : 0u);
        if (state & 0x00010000u) next |= ((b == 'q') ? 0x00020000u : 0u);
        state = next;
    }
    return (state & 0x00020000u) != 0;
}
