/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint32_t regex_trans[22][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { 0 },
    /* position 2 */ { ['c'] = 0x00000018u },
    /* position 3 */ { 0 },
    /* position 4 */ { ['a'] = 0x00000060u },
    /* position 5 */ { 0 },
    /* position 6 */ { ['t'] = 0x00000082u },
    /* position 7 */ { 0 },
    /* position 8 */ { ['d'] = 0x00000600u },
    /* position 9 */ { 0 },
    /* position 10 */ { ['o'] = 0x00001800u },
    /* position 11 */ { 0 },
    /* position 12 */ { ['g'] = 0x00002002u },
    /* position 13 */ { 0 },
    /* position 14 */ { ['f'] = 0x00018000u },
    /* position 15 */ { 0 },
    /* position 16 */ { ['i'] = 0x00060000u },
    /* position 17 */ { 0 },
    /* position 18 */ { ['s'] = 0x00180000u },
    /* position 19 */ { 0 },
    /* position 20 */ { ['h'] = 0x00200002u },
    /* position 21 */ { 0 },
};

/* regex:    "cat|dog|fish"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t)
 */
bool regex_match(const char *input, size_t len) {
    uint32_t state = 0x00004105u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t next = 0;
        if (state & 0x00000004u) next |= regex_trans[2][b];
        if (state & 0x00000010u) next |= regex_trans[4][b];
        if (state & 0x00000040u) next |= regex_trans[6][b];
        if (state & 0x00000100u) next |= regex_trans[8][b];
        if (state & 0x00000400u) next |= regex_trans[10][b];
        if (state & 0x00001000u) next |= regex_trans[12][b];
        if (state & 0x00004000u) next |= regex_trans[14][b];
        if (state & 0x00010000u) next |= regex_trans[16][b];
        if (state & 0x00040000u) next |= regex_trans[18][b];
        if (state & 0x00100000u) next |= regex_trans[20][b];
        state = next;
    }
    return (state & 0x00000002u) != 0;
}
