/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "abcdefghijklmnopqrstuvwxyz012345"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t[2])
 */
bool regex_match(const char *input, size_t len) {
    uint32_t s0 = 0x00000001u;
    uint32_t s1 = 0x00000000u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t n0 = 0;
        uint32_t n1 = 0;
        if (s0 & 0x00000001u) { n0 |= ((b == 'a') ? 0x00000002u : 0u); }
        if (s0 & 0x00000002u) { n0 |= ((b == 'b') ? 0x00000004u : 0u); }
        if (s0 & 0x00000004u) { n0 |= ((b == 'c') ? 0x00000008u : 0u); }
        if (s0 & 0x00000008u) { n0 |= ((b == 'd') ? 0x00000010u : 0u); }
        if (s0 & 0x00000010u) { n0 |= ((b == 'e') ? 0x00000020u : 0u); }
        if (s0 & 0x00000020u) { n0 |= ((b == 'f') ? 0x00000040u : 0u); }
        if (s0 & 0x00000040u) { n0 |= ((b == 'g') ? 0x00000080u : 0u); }
        if (s0 & 0x00000080u) { n0 |= ((b == 'h') ? 0x00000100u : 0u); }
        if (s0 & 0x00000100u) { n0 |= ((b == 'i') ? 0x00000200u : 0u); }
        if (s0 & 0x00000200u) { n0 |= ((b == 'j') ? 0x00000400u : 0u); }
        if (s0 & 0x00000400u) { n0 |= ((b == 'k') ? 0x00000800u : 0u); }
        if (s0 & 0x00000800u) { n0 |= ((b == 'l') ? 0x00001000u : 0u); }
        if (s0 & 0x00001000u) { n0 |= ((b == 'm') ? 0x00002000u : 0u); }
        if (s0 & 0x00002000u) { n0 |= ((b == 'n') ? 0x00004000u : 0u); }
        if (s0 & 0x00004000u) { n0 |= ((b == 'o') ? 0x00008000u : 0u); }
        if (s0 & 0x00008000u) { n0 |= ((b == 'p') ? 0x00010000u : 0u); }
        if (s0 & 0x00010000u) { n0 |= ((b == 'q') ? 0x00020000u : 0u); }
        if (s0 & 0x00020000u) { n0 |= ((b == 'r') ? 0x00040000u : 0u); }
        if (s0 & 0x00040000u) { n0 |= ((b == 's') ? 0x00080000u : 0u); }
        if (s0 & 0x00080000u) { n0 |= ((b == 't') ? 0x00100000u : 0u); }
        if (s0 & 0x00100000u) { n0 |= ((b == 'u') ? 0x00200000u : 0u); }
        if (s0 & 0x00200000u) { n0 |= ((b == 'v') ? 0x00400000u : 0u); }
        if (s0 & 0x00400000u) { n0 |= ((b == 'w') ? 0x00800000u : 0u); }
        if (s0 & 0x00800000u) { n0 |= ((b == 'x') ? 0x01000000u : 0u); }
        if (s0 & 0x01000000u) { n0 |= ((b == 'y') ? 0x02000000u : 0u); }
        if (s0 & 0x02000000u) { n0 |= ((b == 'z') ? 0x04000000u : 0u); }
        if (s0 & 0x04000000u) { n0 |= ((b == '0') ? 0x08000000u : 0u); }
        if (s0 & 0x08000000u) { n0 |= ((b == '1') ? 0x10000000u : 0u); }
        if (s0 & 0x10000000u) { n0 |= ((b == '2') ? 0x20000000u : 0u); }
        if (s0 & 0x20000000u) { n0 |= ((b == '3') ? 0x40000000u : 0u); }
        if (s0 & 0x40000000u) { n0 |= ((b == '4') ? 0x80000000u : 0u); }
        if (s0 & 0x80000000u) { n1 |= ((b == '5') ? 0x00000001u : 0u); }
        s0 = n0;
        s1 = n1;
    }
    return ((s1 & 0x00000001u)) != 0;
}
