/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans_1[256] = { ['c'] = 0x04u };
static const uint8_t regex_trans_2[256] = { ['a'] = 0x08u };
static const uint8_t regex_trans_3[256] = { ['t'] = 0x01u };
static const uint8_t regex_trans_4[256] = { ['d'] = 0x20u };
static const uint8_t regex_trans_5[256] = { ['o'] = 0x40u };
static const uint8_t regex_trans_6[256] = { ['g'] = 0x01u };
static const uint16_t regex_trans_7[256] = { ['f'] = 0x0100u };
static const uint16_t regex_trans_8[256] = { ['i'] = 0x0200u };
static const uint16_t regex_trans_9[256] = { ['s'] = 0x0400u };
static const uint8_t regex_trans_10[256] = { ['h'] = 0x01u };

/* regex:    "cat|dog|fish"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint16_t)
 */
bool regex_match(const char *input, size_t len) {
    uint16_t state = 0x0092u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint16_t next = 0;
        if (state & 0x0002u) next |= regex_trans_1[b];
        if (state & 0x0004u) next |= regex_trans_2[b];
        if (state & 0x0008u) next |= regex_trans_3[b];
        if (state & 0x0010u) next |= regex_trans_4[b];
        if (state & 0x0020u) next |= regex_trans_5[b];
        if (state & 0x0040u) next |= regex_trans_6[b];
        if (state & 0x0080u) next |= regex_trans_7[b];
        if (state & 0x0100u) next |= regex_trans_8[b];
        if (state & 0x0200u) next |= regex_trans_9[b];
        if (state & 0x0400u) next |= regex_trans_10[b];
        state = next;
    }
    return (state & 0x0001u) != 0;
}
