/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint32_t regex_trans[18][256] = {
    /* position 0 */ { ['a'] = 0x00000002u },
    /* position 1 */ { ['b'] = 0x00000004u },
    /* position 2 */ { ['c'] = 0x00000008u },
    /* position 3 */ { ['d'] = 0x00000010u },
    /* position 4 */ { ['e'] = 0x00000020u },
    /* position 5 */ { ['f'] = 0x00000040u },
    /* position 6 */ { ['g'] = 0x00000080u },
    /* position 7 */ { ['h'] = 0x00000100u },
    /* position 8 */ { ['i'] = 0x00000200u },
    /* position 9 */ { ['j'] = 0x00000400u },
    /* position 10 */ { ['k'] = 0x00000800u },
    /* position 11 */ { ['l'] = 0x00001000u },
    /* position 12 */ { ['m'] = 0x00002000u },
    /* position 13 */ { ['n'] = 0x00004000u },
    /* position 14 */ { ['o'] = 0x00008000u },
    /* position 15 */ { ['p'] = 0x00010000u },
    /* position 16 */ { ['q'] = 0x00020000u },
    /* position 17 */ { 0 },
};

/* regex:    "abcdefghijklmnopq"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t)
 */
bool regex_match(const char *input, size_t len) {
    uint32_t state = 0x00000001u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t next = 0;
        if (state & 0x00000001u) next |= regex_trans[0][b];
        if (state & 0x00000002u) next |= regex_trans[1][b];
        if (state & 0x00000004u) next |= regex_trans[2][b];
        if (state & 0x00000008u) next |= regex_trans[3][b];
        if (state & 0x00000010u) next |= regex_trans[4][b];
        if (state & 0x00000020u) next |= regex_trans[5][b];
        if (state & 0x00000040u) next |= regex_trans[6][b];
        if (state & 0x00000080u) next |= regex_trans[7][b];
        if (state & 0x00000100u) next |= regex_trans[8][b];
        if (state & 0x00000200u) next |= regex_trans[9][b];
        if (state & 0x00000400u) next |= regex_trans[10][b];
        if (state & 0x00000800u) next |= regex_trans[11][b];
        if (state & 0x00001000u) next |= regex_trans[12][b];
        if (state & 0x00002000u) next |= regex_trans[13][b];
        if (state & 0x00004000u) next |= regex_trans[14][b];
        if (state & 0x00008000u) next |= regex_trans[15][b];
        if (state & 0x00010000u) next |= regex_trans[16][b];
        state = next;
    }
    return (state & 0x00020000u) != 0;
}
