/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans[6][256] = {
    /* position 0 */ { ['h'] = 0x02u },
    /* position 1 */ { ['e'] = 0x04u },
    /* position 2 */ { ['l'] = 0x08u },
    /* position 3 */ { ['l'] = 0x10u },
    /* position 4 */ { ['o'] = 0x20u },
    /* position 5 */ { 0 },
};

/* regex:    "hello"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= regex_trans[0][b];
        if (state & 0x02u) next |= regex_trans[1][b];
        if (state & 0x04u) next |= regex_trans[2][b];
        if (state & 0x08u) next |= regex_trans[3][b];
        if (state & 0x10u) next |= regex_trans[4][b];
        state = next;
    }
    return (state & 0x20u) != 0;
}
