/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans[4][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { 0 },
    /* position 2 */ { ['0'] = 0x0eu, ['1'] = 0x0eu, ['2'] = 0x0eu, ['3'] = 0x0eu, ['4'] = 0x0eu, ['5'] = 0x0eu, ['6'] = 0x0eu, ['7'] = 0x0eu, ['8'] = 0x0eu, ['9'] = 0x0eu, ['_'] = 0x0eu, ['a'] = 0x0eu, ['b'] = 0x0eu, ['c'] = 0x0eu, ['d'] = 0x0eu, ['e'] = 0x0eu, ['f'] = 0x0eu, ['g'] = 0x0eu, ['h'] = 0x0eu, ['i'] = 0x0eu, ['j'] = 0x0eu, ['k'] = 0x0eu, ['l'] = 0x0eu, ['m'] = 0x0eu, ['n'] = 0x0eu, ['o'] = 0x0eu, ['p'] = 0x0eu, ['q'] = 0x0eu, ['r'] = 0x0eu, ['s'] = 0x0eu, ['t'] = 0x0eu, ['u'] = 0x0eu, ['v'] = 0x0eu, ['w'] = 0x0eu, ['x'] = 0x0eu, ['y'] = 0x0eu, ['z'] = 0x0eu },
    /* position 3 */ { 0 },
};

/* regex:    "[a-z0-9_]+"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x05u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x04u) next |= regex_trans[2][b];
        state = next;
    }
    return (state & 0x02u) != 0;
}
