/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

static const uint8_t regex_trans[4][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { 0 },
    /* position 2 */ { ['0'] = 0x0eu, ['1'] = 0x0eu, ['2'] = 0x0eu, ['3'] = 0x0eu, ['4'] = 0x0eu, ['5'] = 0x0eu, ['6'] = 0x0eu, ['7'] = 0x0eu, ['8'] = 0x0eu, ['9'] = 0x0eu },
    /* position 3 */ { 0 },
};

/* regex:    "\d+"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x05u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x04u) next |= regex_trans[2][b];
        state = next;
    }
    return (state & 0x02u) != 0;
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <input>\n", argv[0]);
        return 2;
    }
    return regex_match(argv[1], strlen(argv[1])) ? 0 : 1;
}
