/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

static const uint8_t regex_transitions[3][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { ['0'] = 2, ['1'] = 2, ['2'] = 2, ['3'] = 2, ['4'] = 2, ['5'] = 2, ['6'] = 2, ['7'] = 2, ['8'] = 2, ['9'] = 2 },
    /* state 2 */ { ['0'] = 2, ['1'] = 2, ['2'] = 2, ['3'] = 2, ['4'] = 2, ['5'] = 2, ['6'] = 2, ['7'] = 2, ['8'] = 2, ['9'] = 2 },
};

/* regex:                "\d+"
 * flags:                ""
 * encoding:             utf8
 * alphabet-compression: no
 * row-deduplication:    no
 * early-exit:           no
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[state][(unsigned char)input[i]];
    }
    return state >= 2;
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <input>\n", argv[0]);
        return 2;
    }
    return regex_match(argv[1], strlen(argv[1])) ? 0 : 1;
}
