/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

static const uint8_t regex_trans_1[256] = { ['0'] = 0x03u, ['1'] = 0x03u, ['2'] = 0x03u, ['3'] = 0x03u, ['4'] = 0x03u, ['5'] = 0x03u, ['6'] = 0x03u, ['7'] = 0x03u, ['8'] = 0x03u, ['9'] = 0x03u };

/* regex:    "\d+"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x02u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x02u) next |= regex_trans_1[b];
        state = next;
    }
    return (state & 0x01u) != 0;
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <input>\n", argv[0]);
        return 2;
    }
    return regex_match(argv[1], strlen(argv[1])) ? 0 : 1;
}
