/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint16_t regex_trans[11][256] = {
    /* position 0 */ { ['0'] = 0x0002u, ['1'] = 0x0002u, ['2'] = 0x0002u, ['3'] = 0x0002u, ['4'] = 0x0002u, ['5'] = 0x0002u, ['6'] = 0x0002u, ['7'] = 0x0002u, ['8'] = 0x0002u, ['9'] = 0x0002u },
    /* position 1 */ { ['0'] = 0x0004u, ['1'] = 0x0004u, ['2'] = 0x0004u, ['3'] = 0x0004u, ['4'] = 0x0004u, ['5'] = 0x0004u, ['6'] = 0x0004u, ['7'] = 0x0004u, ['8'] = 0x0004u, ['9'] = 0x0004u },
    /* position 2 */ { ['0'] = 0x0008u, ['1'] = 0x0008u, ['2'] = 0x0008u, ['3'] = 0x0008u, ['4'] = 0x0008u, ['5'] = 0x0008u, ['6'] = 0x0008u, ['7'] = 0x0008u, ['8'] = 0x0008u, ['9'] = 0x0008u },
    /* position 3 */ { ['0'] = 0x0010u, ['1'] = 0x0010u, ['2'] = 0x0010u, ['3'] = 0x0010u, ['4'] = 0x0010u, ['5'] = 0x0010u, ['6'] = 0x0010u, ['7'] = 0x0010u, ['8'] = 0x0010u, ['9'] = 0x0010u },
    /* position 4 */ { ['-'] = 0x0020u },
    /* position 5 */ { ['0'] = 0x0040u, ['1'] = 0x0040u, ['2'] = 0x0040u, ['3'] = 0x0040u, ['4'] = 0x0040u, ['5'] = 0x0040u, ['6'] = 0x0040u, ['7'] = 0x0040u, ['8'] = 0x0040u, ['9'] = 0x0040u },
    /* position 6 */ { ['0'] = 0x0080u, ['1'] = 0x0080u, ['2'] = 0x0080u, ['3'] = 0x0080u, ['4'] = 0x0080u, ['5'] = 0x0080u, ['6'] = 0x0080u, ['7'] = 0x0080u, ['8'] = 0x0080u, ['9'] = 0x0080u },
    /* position 7 */ { ['-'] = 0x0100u },
    /* position 8 */ { ['0'] = 0x0200u, ['1'] = 0x0200u, ['2'] = 0x0200u, ['3'] = 0x0200u, ['4'] = 0x0200u, ['5'] = 0x0200u, ['6'] = 0x0200u, ['7'] = 0x0200u, ['8'] = 0x0200u, ['9'] = 0x0200u },
    /* position 9 */ { ['0'] = 0x0400u, ['1'] = 0x0400u, ['2'] = 0x0400u, ['3'] = 0x0400u, ['4'] = 0x0400u, ['5'] = 0x0400u, ['6'] = 0x0400u, ['7'] = 0x0400u, ['8'] = 0x0400u, ['9'] = 0x0400u },
    /* position 10 */ { 0 },
};

/* regex:    "\d{4}-\d{2}-\d{2}"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint16_t)
 */
bool regex_match(const char *input, size_t len) {
    uint16_t state = 0x0001u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint16_t next = 0;
        if (state & 0x0001u) next |= regex_trans[0][b];
        if (state & 0x0002u) next |= regex_trans[1][b];
        if (state & 0x0004u) next |= regex_trans[2][b];
        if (state & 0x0008u) next |= regex_trans[3][b];
        if (state & 0x0010u) next |= regex_trans[4][b];
        if (state & 0x0020u) next |= regex_trans[5][b];
        if (state & 0x0040u) next |= regex_trans[6][b];
        if (state & 0x0080u) next |= regex_trans[7][b];
        if (state & 0x0100u) next |= regex_trans[8][b];
        if (state & 0x0200u) next |= regex_trans[9][b];
        state = next;
    }
    return (state & 0x0400u) != 0;
}
