/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans_1[256] = { [9] = 0x03u, [10] = 0x03u, [12] = 0x03u, [13] = 0x03u, [' '] = 0x03u };

/* regex:    "\s+"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x02u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x02u) next |= regex_trans_1[b];
        state = next;
    }
    return (state & 0x01u) != 0;
}
