/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint32_t regex_trans[20][256] = {
    /* position 0 */ { ['0'] = 0x00000006u, ['1'] = 0x00000006u, ['2'] = 0x00000006u, ['3'] = 0x00000006u, ['4'] = 0x00000006u, ['5'] = 0x00000006u, ['6'] = 0x00000006u, ['7'] = 0x00000006u, ['8'] = 0x00000006u, ['9'] = 0x00000006u },
    /* position 1 */ { 0 },
    /* position 2 */ { ['0'] = 0x00000018u, ['1'] = 0x00000018u, ['2'] = 0x00000018u, ['3'] = 0x00000018u, ['4'] = 0x00000018u, ['5'] = 0x00000018u, ['6'] = 0x00000018u, ['7'] = 0x00000018u, ['8'] = 0x00000018u, ['9'] = 0x00000018u },
    /* position 3 */ { 0 },
    /* position 4 */ { ['0'] = 0x00000060u, ['1'] = 0x00000060u, ['2'] = 0x00000060u, ['3'] = 0x00000060u, ['4'] = 0x00000060u, ['5'] = 0x00000060u, ['6'] = 0x00000060u, ['7'] = 0x00000060u, ['8'] = 0x00000060u, ['9'] = 0x00000060u },
    /* position 5 */ { 0 },
    /* position 6 */ { ['0'] = 0x00000180u, ['1'] = 0x00000180u, ['2'] = 0x00000180u, ['3'] = 0x00000180u, ['4'] = 0x00000180u, ['5'] = 0x00000180u, ['6'] = 0x00000180u, ['7'] = 0x00000180u, ['8'] = 0x00000180u, ['9'] = 0x00000180u },
    /* position 7 */ { 0 },
    /* position 8 */ { ['-'] = 0x00000600u },
    /* position 9 */ { 0 },
    /* position 10 */ { ['0'] = 0x00001800u, ['1'] = 0x00001800u, ['2'] = 0x00001800u, ['3'] = 0x00001800u, ['4'] = 0x00001800u, ['5'] = 0x00001800u, ['6'] = 0x00001800u, ['7'] = 0x00001800u, ['8'] = 0x00001800u, ['9'] = 0x00001800u },
    /* position 11 */ { 0 },
    /* position 12 */ { ['0'] = 0x00006000u, ['1'] = 0x00006000u, ['2'] = 0x00006000u, ['3'] = 0x00006000u, ['4'] = 0x00006000u, ['5'] = 0x00006000u, ['6'] = 0x00006000u, ['7'] = 0x00006000u, ['8'] = 0x00006000u, ['9'] = 0x00006000u },
    /* position 13 */ { 0 },
    /* position 14 */ { ['-'] = 0x00018000u },
    /* position 15 */ { 0 },
    /* position 16 */ { ['0'] = 0x00060000u, ['1'] = 0x00060000u, ['2'] = 0x00060000u, ['3'] = 0x00060000u, ['4'] = 0x00060000u, ['5'] = 0x00060000u, ['6'] = 0x00060000u, ['7'] = 0x00060000u, ['8'] = 0x00060000u, ['9'] = 0x00060000u },
    /* position 17 */ { 0 },
    /* position 18 */ { ['0'] = 0x00080000u, ['1'] = 0x00080000u, ['2'] = 0x00080000u, ['3'] = 0x00080000u, ['4'] = 0x00080000u, ['5'] = 0x00080000u, ['6'] = 0x00080000u, ['7'] = 0x00080000u, ['8'] = 0x00080000u, ['9'] = 0x00080000u },
    /* position 19 */ { 0 },
};

/* regex:    "\d{4}-\d{2}-\d{2}"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t)
 */
bool regex_match(const char *input, size_t len) {
    uint32_t state = 0x00000001u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t next = 0;
        if (state & 0x00000001u) next |= regex_trans[0][b];
        if (state & 0x00000004u) next |= regex_trans[2][b];
        if (state & 0x00000010u) next |= regex_trans[4][b];
        if (state & 0x00000040u) next |= regex_trans[6][b];
        if (state & 0x00000100u) next |= regex_trans[8][b];
        if (state & 0x00000400u) next |= regex_trans[10][b];
        if (state & 0x00001000u) next |= regex_trans[12][b];
        if (state & 0x00004000u) next |= regex_trans[14][b];
        if (state & 0x00010000u) next |= regex_trans[16][b];
        if (state & 0x00040000u) next |= regex_trans[18][b];
        state = next;
    }
    return (state & 0x00080000u) != 0;
}
