/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans_1[256] = { ['a'] = 0x03u, ['b'] = 0x03u, ['c'] = 0x03u, ['d'] = 0x03u, ['e'] = 0x03u, ['f'] = 0x03u, ['g'] = 0x03u, ['h'] = 0x03u, ['i'] = 0x03u, ['j'] = 0x03u, ['k'] = 0x03u, ['l'] = 0x03u, ['m'] = 0x03u, ['n'] = 0x03u, ['o'] = 0x03u, ['p'] = 0x03u, ['q'] = 0x03u, ['r'] = 0x03u, ['s'] = 0x03u, ['t'] = 0x03u, ['u'] = 0x03u, ['v'] = 0x03u, ['w'] = 0x03u, ['x'] = 0x03u, ['y'] = 0x03u, ['z'] = 0x03u };

/* regex:    "(?x) [a-z]+ # letters"
 * flags:    "x"
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x02u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x02u) next |= regex_trans_1[b];
        state = next;
    }
    return (state & 0x01u) != 0;
}
