/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans[7][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { 0 },
    /* position 2 */ { ['A'] = 0x0eu, ['B'] = 0x0eu, ['C'] = 0x0eu, ['D'] = 0x0eu, ['E'] = 0x0eu, ['F'] = 0x0eu, ['G'] = 0x0eu, ['H'] = 0x0eu, ['I'] = 0x0eu, ['J'] = 0x0eu, ['K'] = 0x0eu, ['L'] = 0x0eu, ['M'] = 0x0eu, ['N'] = 0x0eu, ['O'] = 0x0eu, ['P'] = 0x0eu, ['Q'] = 0x0eu, ['R'] = 0x0eu, ['S'] = 0x0eu, ['T'] = 0x0eu, ['U'] = 0x0eu, ['V'] = 0x0eu, ['W'] = 0x0eu, ['X'] = 0x0eu, ['Y'] = 0x0eu, ['Z'] = 0x0eu, ['a'] = 0x0eu, ['b'] = 0x0eu, ['c'] = 0x0eu, ['d'] = 0x0eu, ['e'] = 0x0eu, ['f'] = 0x0eu, ['g'] = 0x0eu, ['h'] = 0x0eu, ['i'] = 0x0eu, ['j'] = 0x0eu, ['k'] = 0x0eu, ['l'] = 0x0eu, ['m'] = 0x0eu, ['n'] = 0x0eu, ['o'] = 0x0eu, ['p'] = 0x0eu, ['q'] = 0x0eu, ['r'] = 0x0eu, ['s'] = 0x0eu, ['t'] = 0x0eu, ['u'] = 0x0eu, ['v'] = 0x0eu, ['w'] = 0x0eu, ['x'] = 0x0eu, ['y'] = 0x0eu, ['z'] = 0x0eu, [197] = 0x40u, [226] = 0x10u },
    /* position 3 */ { 0 },
    /* position 4 */ { [132] = 0x20u },
    /* position 5 */ { [170] = 0x0eu },
    /* position 6 */ { [191] = 0x0eu },
};

/* regex:    "[a-z]+"
 * flags:    "i"
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x05u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x04u) next |= regex_trans[2][b];
        if (state & 0x10u) next |= regex_trans[4][b];
        if (state & 0x20u) next |= regex_trans[5][b];
        if (state & 0x40u) next |= regex_trans[6][b];
        state = next;
    }
    return (state & 0x02u) != 0;
}
