/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t my_matcher_transitions[3][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { ['a'] = 2, ['b'] = 2, ['c'] = 2, ['d'] = 2, ['e'] = 2, ['f'] = 2, ['g'] = 2, ['h'] = 2, ['i'] = 2, ['j'] = 2, ['k'] = 2, ['l'] = 2, ['m'] = 2, ['n'] = 2, ['o'] = 2, ['p'] = 2, ['q'] = 2, ['r'] = 2, ['s'] = 2, ['t'] = 2, ['u'] = 2, ['v'] = 2, ['w'] = 2, ['x'] = 2, ['y'] = 2, ['z'] = 2 },
    /* state 2 */ { ['a'] = 2, ['b'] = 2, ['c'] = 2, ['d'] = 2, ['e'] = 2, ['f'] = 2, ['g'] = 2, ['h'] = 2, ['i'] = 2, ['j'] = 2, ['k'] = 2, ['l'] = 2, ['m'] = 2, ['n'] = 2, ['o'] = 2, ['p'] = 2, ['q'] = 2, ['r'] = 2, ['s'] = 2, ['t'] = 2, ['u'] = 2, ['v'] = 2, ['w'] = 2, ['x'] = 2, ['y'] = 2, ['z'] = 2 },
};

/* regex:                "[a-z]+"
 * flags:                ""
 * encoding:             utf8
 * alphabet-compression: no
 * row-deduplication:    no
 * early-exit:           no
 */
bool my_matcher_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = my_matcher_transitions[state][(unsigned char)input[i]];
    }
    return state >= 2;
}
