/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_transitions[8][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { ['c'] = 4 },
    /* state 2 */ { ['o'] = 5 },
    /* state 3 */ { ['l'] = 2 },
    /* state 4 */ { ['o'] = 3 },
    /* state 5 */ { ['r'] = 7, ['u'] = 6 },
    /* state 6 */ { ['r'] = 7 },
    /* state 7 */ { 0 },
};

/* regex:                "colou?r"
 * flags:                ""
 * encoding:             utf8
 * alphabet-compression: no
 * row-deduplication:    no
 * early-exit:           no
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[state][(unsigned char)input[i]];
    }
    return state >= 7;
}
