/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_transitions[5][256] = {
    /* states 0, 3 */ { 0 },
    /* state 1 */ { ['a'] = 2 },
    /* state 2 */ { ['a'] = 4 },
    /* state 4 */ { ['a'] = 5 },
    /* state 5 */ { ['a'] = 3 },
};

static const uint8_t regex_row_map[6] = {
    0, 1, 2, 0, 3, 4
};

bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[regex_row_map[state]][(unsigned char)input[i]];
    }
    return state >= 3;
}
