/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans_0[256] = { ['a'] = 0x06u };
static const uint8_t regex_trans_1[256] = { ['b'] = 0x06u };
static const uint8_t regex_trans_2[256] = { ['c'] = 0x08u };

/* regex:    "ab*c"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= regex_trans_0[b];
        if (state & 0x02u) next |= regex_trans_1[b];
        if (state & 0x04u) next |= regex_trans_2[b];
        state = next;
    }
    return (state & 0x08u) != 0;
}
