/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans[8][256] = {
    /* position 0 */ { ['a'] = 0x5eu },
    /* position 1 */ { 0 },
    /* position 2 */ { 0 },
    /* position 3 */ { 0 },
    /* position 4 */ { ['b'] = 0x78u },
    /* position 5 */ { 0 },
    /* position 6 */ { ['c'] = 0x80u },
    /* position 7 */ { 0 },
};

/* regex:    "ab*c"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= regex_trans[0][b];
        if (state & 0x10u) next |= regex_trans[4][b];
        if (state & 0x40u) next |= regex_trans[6][b];
        state = next;
    }
    return (state & 0x80u) != 0;
}
