/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans[5][256] = {
    /* position 0 */ { 0 },
    /* position 1 */ { 0 },
    /* position 2 */ { [195] = 0x10u },
    /* position 3 */ { 0 },
    /* position 4 */ { [169] = 0x0eu },
};

/* regex:    "\x{00e9}+"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x05u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x04u) next |= regex_trans[2][b];
        if (state & 0x10u) next |= regex_trans[4][b];
        state = next;
    }
    return (state & 0x02u) != 0;
}
