/* Generated by regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_transitions[4][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { [195] = 2 },
    /* state 2 */ { [169] = 3 },
    /* state 3 */ { [195] = 2 },
};

/* regex:                "\x{00e9}+"
 * flags:                ""
 * encoding:             utf8
 * alphabet-compression: no
 * row-deduplication:    no
 * early-exit:           no
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[state][(unsigned char)input[i]];
    }
    return state >= 3;
}
